services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: true
      TYPE: MODRINTH
      MEMORY: 4G
      MODRINTH_MODPACK: better-mc-forge-bmc4
      MODRINTH_VERSION: v4
      MODRINTH_FORCE_SYNCHRONIZE: true
      MODRINTH_EXCLUDE_FILES: |
        citresewn
        oculus
        yungsmenutweaks
        notenoughanimations
        ryoamiclights
        euphoriapatcher
        entity_model_features
        entity_texture_features
        3dskinlayers
      MODRINTH_OVERRIDES_EXCLUSIONS: |
        mods/NekosEnchantedBooks-*.jar
        mods/citresewn-*.jar
      DEBUG: true
      SETUP_ONLY: true
    volumes:
      - data:/data
    ports:
      - "25565:25565"

volumes:
  data: {}