services:
  mc:
    image: itzg/minecraft-server:java17
    environment:
      DEBUG: true
      SETUP_ONLY: true
      EULA: true
      TYPE: MODRINTH
      VERSION: 1.20.1
      MEMORY: 4G
      MODRINTH_MODPACK: better-mc-forge-bmc4
      MODRINTH_VERSION: v28
      MODRINTH_OVERRIDES_EXCLUSIONS: |
        mods/NekosEnchantedBooks-*.jar
        mods/citresewn-*.jar
    volumes:
      - data:/data
    ports:
      - "25565:25565"

volumes:
  data: {}