services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: true
      MOD_PLATFORM: MODRINTH
      MODRINTH_MODPACK: https://modrinth.com/modpack/better-mc-forge-bmc4/version/v32.5
      MODRINTH_EXCLUDE_FILES: |
        XaeroPlus
        XaerosWorldMap
      MODRINTH_OVERRIDES_EXCLUSIONS: |
        mods/citresewn-*.jar
        **/datapacks/BE_default_endgen_fix*
      MODRINTH_FORCE_SYNCHRONIZE: true
      MEMORY: 4G
    ports:
      - "25565:25565"
    # declare /data volume mapping as desired
#    volumes:
#      - ./data:/data