services:
  minecraft:
    image: itzg/minecraft-server
    volumes:
      - ./data:/data
      - ./mods:/mods
    ports:
      - "25565:25565"
    environment:
      EULA: "true"
      TYPE: "FORGE"
      VERSION: "1.19.2"
    tty: true
    stdin_open: true