services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: true
      TYPE: SPIGOT
      VERSION: 1.20.4
    ports:
      - "25565:25565"
    volumes:
      - data:/data
volumes:
  data: {}
