#!/bin/bash

. /start-dns-utils/dns_checker.sh
. /start-dns-utils/is_valid.sh


if [ -n "$DNS_PROVIDER" ]; then
    provider_path="/start-dns-utils/providers/${DNS_PROVIDER}"
    if [ -f $provider_path ]; then
        . $provider_path
    else
        echo "$DNS_PROVIDER is not a supported DNS provider."
        echo "Select from one of these:"
        echo
        echo "$(ls /start-dns-utils/providers/)"
        exit
    fi
else
  echo "ITS NOT WORKING"
fi

provider_checks

if [ -n $MC_DOMAIN ]; then
    domain=$MC_DOMAIN
else
    echo "MC_DOMAIN is not defined. Skipping DNS logic."
    exit
fi

if [ -n $MC_PORT ] && is_valid_int $MC_PORT; then
    port=$MC_PORT
fi

if [ -n $MC_IP ] && is_valid_ip $MC_IP; then
    ip=$MC_IP
fi

timeout=60
start_time=$(date +%s)
while [ -z port ] || [ -z ip ]; do
    current_time=$(date +%s)
    elapsed=$((current_time - start_time))
    if (( elapsed >= timeout )); then
        echo "Timeout reached."
        break
    fi
    if [ -z $port ]; then
        if [ -f $MC_PORT ]; then
            port_candidate=$(cat $MC_PORT)
            if is_valid_int $port_candidate; then
                port=$port_candidate
            else
                echo "The value in the port file is not valid. SRV record generation will fail."
                port="FAILED"
            fi
        fi
    fi
    if [ -z $ip ]; then
        if [ -f $MC_IP ]; then
            ip_candidate=$(cat $MC_IP)
            if is_valid_int $ip_candidate; then
                ip=$ip_candidate
            else
                echo "The value in the ip file is not valid. A and AAAA record generation will fail."
                ip="FAILED"
            fi
        fi
    fi
    sleep 1
done

read current_ip current_port <<< "$(check_srv_record $MC_DOMAIN)"

if [ "$current_port" != "$port" ] && [ "$port" != "FAILED" ]; then
    update_srv
fi

if [ "$current_ip" != "$ip" ] && [ $ip != "FAILED" ]; then
    update_a
fi

exec "${SCRIPTS:-/}start-configuration" "$@"
