services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: true
      MODPACK_PLATFORM: AUTO_CURSEFORGE
      # from .env
      CF_API_KEY: ${CF_API_KEY}
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/all-of-fabric-7
#      CF_FILENAME_MATCHER: 1.2.2
      CF_OVERRIDES_EXCLUSIONS: |
        mods/iris*.jar
        mods/sodium*.jar
      MEMORY: 4G
    ports:
      - "25565:25565"
    volumes:
      - mc-data:/data

volumes:
  mc-data: {}

